import { readFileSync } from "node:fs";

import type { Page } from "@playwright/test";
import { expect, test } from "@playwright/test";

import { expectNoAxeViolations } from "../support/axe.js";
import { expectNothingFailedToRender } from "../support/app.js";
import { BARS_ROUTE_PATTERN } from "../support/pair.js";

// **Acceptance criterion 3, as a picture** (Task 2.13.8).
//
// > "5 days" is five trading sessions across a week containing a holiday.
//
// ## Why this window cannot be reached through the control, which is the first
// thing to know before reading a stubbed route in this suite
//
// The week is `2026-11-23 … 2026-11-30`. **It is in the future.** `VOLUME-AND-
// WINDOW.md` §4(a) settled the address as `?sessions=N` — a **count**, which the
// server resolves against the market date it is answering on — and there is no
// absolute form in the address at all: `bar-series-query.ts` supports one,
// `paths.ts` does not write one and `use-time-window.ts` does not read one.
// Epic 13's scrubber is what introduces one, and adding it here to satisfy a
// test would be scope creep into another epic's vocabulary.
//
// So no press of any cell and no hand-typed URL reaches Thanksgiving from
// September, and the task's instruction *prove it through the control* is not
// satisfiable as written. What is done instead is the next strongest thing, in
// two halves:
//
//  1. **The request and the resolution**, at the layer that owns them.
//     `apps/backend/src/routes/market-data.test.ts` drives the shipped route
//     through `app.inject()` with its clock seam pinned to 2026-11-30 and
//     asserts the five sessions the calendar resolves.
//  2. **The picture**, here, from the body that arrangement produced —
//     `apps/frontend/src/fixtures/bar-series/holiday-week.json`. The axis, the
//     seams, the ticks and the coverage are **all computed client-side from
//     `coverage.requested`**, so everything under test below is entirely real
//     even though the response was handed over by Playwright rather than by a
//     store. The body itself is argued in `fixtures/bar-series.ts`: it was
//     generated by this product's own server against the checked-in calendar
//     rather than typed, which is the distinction that makes it admissible.
//
// ## What is already held elsewhere and is deliberately not re-derived
//
// `chart-geometry.test.ts` holds the whole week at the **axis** level from
// `lastMarketSessions(5, 2026-11-30)`: five sessions, the half day at 210 slots,
// 1,770 in total, no tick labelled `Nov 26`, and — the assertion that actually
// rules out an empty afternoon — **14:00 ET on the half day answering
// `boundary`** rather than a position, the same answer the axis gives a night or
// a weekend. A continuous time axis would have handed that instant 180 slots of
// empty plot and every state test would still have passed.
//
// What is missing below that level, and is therefore what this file is for, is
// the **rendering**: that the picture a person sees has four seams rather than
// five, and that the band between the fourth seam and the fifth session is
// **narrower than the others in the proportion 210 : 390**.

const EXPLORER = "/securities/NVDA";

/**
 * The body, read off disk rather than imported.
 *
 * This package declares `@marketpulse/shared` and nothing else — pnpm links a
 * workspace package only into packages that declare it — so a spec cannot
 * `import` from `apps/frontend`. Reading the file is also the honest shape: what
 * is being served here is a **recorded response**, not a module.
 */
const HOLIDAY_WEEK = readFileSync(
  new URL(
    "../../apps/frontend/src/fixtures/bar-series/holiday-week.json",
    import.meta.url,
  ),
  "utf8",
);

/** The five sessions, oldest first — and the one that is missing. */
const SESSIONS = ["Nov 23", "Nov 24", "Nov 25", "Nov 27", "Nov 30"] as const;
const THANKSGIVING = "Nov 26";

/** Slots per session in this window: 390, except the half day's 210. */
const SLOTS = [390, 390, 390, 210, 390] as const;
const TOTAL = SLOTS.reduce((sum, slots) => sum + slots, 0);

function priceRegion(page: Page) {
  return page.getByRole("region", { name: "Price" });
}

function volumeRegion(page: Page) {
  return page.getByRole("region", { name: "Volume" });
}

function plot(page: Page) {
  return priceRegion(page).locator("svg:has(line)");
}

function volumePlot(page: Page) {
  return volumeRegion(page).locator("svg:has(line)");
}

/** Serve the recorded week for every bars request this page makes. */
async function serveTheHolidayWeek(page: Page): Promise<void> {
  await page.route(BARS_ROUTE_PATTERN, async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: HOLIDAY_WEEK,
    });
  });
}

/**
 * Every vertical mark on a plot, as a fraction of the plot's width.
 *
 * The same locator `security-price-chart.spec.ts` uses for the two plots'
 * alignment — a `<line>` whose `x1` equals its `x2`. On a **complete** answer
 * those are the session seams and nothing else: there is no coverage edge,
 * because nothing is uncovered.
 */
async function seamFractions(locator: ReturnType<typeof plot>) {
  const width = (await locator.boundingBox())?.width ?? 0;
  expect(width).toBeGreaterThan(0);

  const xs = await locator.locator("line").evaluateAll((lines) =>
    lines
      .filter((line) => line.getAttribute("x1") === line.getAttribute("x2"))
      .map((line) => Number(line.getAttribute("x1")))
      .sort((a, b) => a - b),
  );

  return xs.map((x) => x / width);
}

test("five sessions across a week with a holiday in it, drawn", async ({
  page,
}) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await serveTheHolidayWeek(page);
  await page.goto(EXPLORER);

  await expect(plot(page)).toBeVisible();
  // **The bar count moved to the chart's own text alternative** on 2026-09-14,
  // when the panel's coverage sentence came off. It is the same figure from the
  // same body and it is still the thing that says this fixture was served: no
  // store on any runner holds a week that has not happened.
  await expect(priceRegion(page)).toContainText("1,770 closing prices");

  // **Four seams and not five.** A naive window would have put one between
  // Wednesday and Friday for a Thursday that never opened.
  const seams = await seamFractions(plot(page));
  expect(seams).toHaveLength(SESSIONS.length - 1);

  // And they fall where the slot arithmetic says. The assertion that matters is
  // the **fourth band**: a half day drawn as a whole one would put every seam at
  // a fifth of the frame and leave three hours of empty plot between the last
  // bar of `Nov 27` and the first of `Nov 30`.
  const expected: number[] = [];
  let cumulative = 0;
  for (const slots of SLOTS.slice(0, -1)) {
    cumulative += slots;
    expected.push(cumulative / TOTAL);
  }

  for (const [index, seam] of seams.entries())
    expect(seam, `seam ${String(index)}`).toBeCloseTo(expected[index] ?? -1, 2);

  // Said once more as the thing a reader would notice, because the fractions
  // above are easy to read as arithmetic rather than as a picture: the band
  // holding the half day is a little over half the width of the others.
  const bands = [...seams, 1].map(
    (seam, index) => seam - (seams[index - 1] ?? 0),
  );
  expect(bands[3] ?? -1).toBeCloseTo((bands[2] ?? 1) * (210 / 390), 2);

  await expectNothingFailedToRender(page);
});

test("the axis labels the sessions that happened and not the one that did not", async ({
  page,
}) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await serveTheHolidayWeek(page);
  await page.goto(EXPLORER);
  await expect(plot(page)).toBeVisible();

  // The time labels live under the plot, outside the SVG, and are `aria-hidden`
  // — they are sampled and niced, so read aloud they are bare dates with no
  // subject. `getByText` reaches hidden text; `toBeVisible` would not.
  const labels = await priceRegion(page)
    .locator("[aria-hidden='true']")
    .allInnerTexts();
  const axis = labels.join(" ");

  for (const session of SESSIONS) expect(axis).toContain(session);
  expect(axis).not.toContain(THANKSGIVING);

  await expectNothingFailedToRender(page);
});

test("both plots divide the holiday week identically", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await serveTheHolidayWeek(page);
  await page.goto(EXPLORER);
  await expect(plot(page)).toBeVisible();
  await expect(volumePlot(page)).toBeVisible();

  // One axis, two pictures — asserted here as well as in
  // `security-price-chart.spec.ts` because this is the one window in the suite
  // whose sessions are **not all the same width**, which is the case a second
  // derivation would most plausibly get differently.
  expect(await seamFractions(volumePlot(page))).toEqual(
    await seamFractions(plot(page)),
  );

  await expectNothingFailedToRender(page);
});

test("what a listener is told about the holiday week", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 });
  await serveTheHolidayWeek(page);
  await page.goto(EXPLORER);
  await expect(plot(page)).toBeVisible();

  // **Five sessions over seven calendar days**, which is the fact a clause
  // counting elapsed time would get wrong by three — one for the holiday and
  // two for the weekend, none of which this axis gives any width to. The count
  // comes off `timeAxis`, the same function the seams above come off, so the
  // sentence and the picture cannot disagree.
  await expect(priceRegion(page).getByText(/NVDA price chart:/)).toContainText(
    "The frame is drawn across 5 trading sessions.",
  );
  await expect(
    volumeRegion(page).getByText(/NVDA volume chart:/),
  ).toContainText("The frame is drawn across 5 trading sessions.");

  await expectNoAxeViolations(page, "the security route, a holiday week");
  await expectNothingFailedToRender(page);
});
